VGSShop/Areas/Admin/Controllers/AdminOrdersController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;
using PagedList.Core;
using VGSShop.Models;

namespace VGSShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize()]
    public class AdminOrdersController : Controller
    {
        private readonly VGSShopContext _context;
        public INotyfService _notyfService { get; }
        public AdminOrdersController(VGSShopContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        // GET: Admin/AdminOrders
        public IActionResult Index(int? page, int TransactStatusID = 0)
        {
            if (!User.Identity.IsAuthenticated) Response.Redirect("/dang-nhap-admin.html");
            var taiKhoanID = HttpContext.Session.GetString("AccountId");
            if (taiKhoanID == null) return RedirectToAction("Login", "Account", new { Area = "Admin" });
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 20; //20
            List<Order> lsNews = new List<Order>();
            if (TransactStatusID != 0)
            {
                lsNews = _context.Orders
                .AsNoTracking()
                .Where(x => x.TransactStatusId == TransactStatusID)
                .Include(x => x.Customer)
                .Include(o => o.TransactStatus)
                .Where(x => x.Deleted == false)
                .OrderByDescending(x => x.OrderDate).ToList();

            }
            else
            {
                lsNews = _context.Orders
                .AsNoTracking()
                .Include(x => x.Customer)
                .Include(x => x.TransactStatus)
                .Where(x =>x.Deleted==false)
                .OrderByDescending(x => x.OrderDate).ToList();

            }
            PagedList<Order> models = new PagedList<Order>(lsNews.AsQueryable(), pageNumber, pageSize);         
            ViewBag.TransactStatusID = TransactStatusID;
            ViewBag.CurrentPage = pageNumber;
            ViewData["TrangThaiDonHang"] = new SelectList(_context.TransactStatuses, "TransactStatusId", "Status", TransactStatusID);
            return View(models);
        }
        public IActionResult Filtter(int TransactStatusID = 0)
        {
            var url = $"/Admin/AdminOrders?TransactStatusID={TransactStatusID}";
            if (TransactStatusID == 0)
            {
                url = $"/Admin/AdminOrders";
            }
            return Json(new { status = "success", redirectUrl = url });
        }
        public async Task<IActionResult> ChangeStatus(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var order = await _context.Orders.AsNoTracking().Include(x => x.Customer).FirstOrDefaultAsync(x => x.OrderId == id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["TrangThai"] = new SelectList(_context.TransactStatuses, "TransactStatusId", "Status", order.TransactStatusId);
            return PartialView("ChangeStatus", order);
        }
        [HttpPost]
        public async Task<IActionResult> ChangeStatus(int id, [Bind("OrderId,CustomerId,OrderDate,ShipDate,TransactStatusId,Deleted,Paid,PaymentDate,PaymentId,Note,TotalMoney,Address,LocationId,District,Ward")] Order order)
        {
            if(id != order.OrderId)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    var donhang = await _context.Orders.AsNoTracking().Include(x => x.Customer).FirstOrDefaultAsync(x => x.OrderId == id);
                    if(donhang != null)
                    {
                        donhang.Paid = order.Paid;
                        donhang.Deleted = order.Deleted;
                        donhang.TransactStatusId = order.TransactStatusId;
                        if(donhang.Paid == true)
                        {
                            donhang.PaymentDate = DateTime.Now;
                        }
                        if (donhang.TransactStatusId == 5) donhang.Deleted = true;
                        if (donhang.TransactStatusId == 3) donhang.ShipDate = DateTime.Now;
                    }
                    _context.Update(donhang);
                    await _context.SaveChangesAsync();
                    _notyfService.Success("Cập nhật trạng thấy thành công thành công");
                }
                catch(DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.OrderId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            ViewData["TrangThai"] = new SelectList(_context.TransactStatuses, "TransactStatusId", "Status", order.TransactStatusId);
            return PartialView("ChangeStatus", order);
        }

        // GET: Admin/AdminOrders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.Customer)
                .Include(o => o.TransactStatus)
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (order == null)
            {
                return NotFound();
            }

            var chitietdonhang = _context.OrderDetails
                .Include(x => x.Product)
                .AsNoTracking()
                .Where(x => x.OrderId == order.OrderId)
                .OrderBy(x => x.OrderDetailId)
                .ToList();
            ViewBag.ChiTiet = chitietdonhang;
            return View(order);
        }

        // GET: Admin/AdminOrders/Create
        public IActionResult Create()
        {
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustomerId", "CustomerId");
            ViewData["TransactStatusId"] = new SelectList(_context.TransactStatuses, "TransactStatusId", "TransactStatusId");
            return View();
        }

        // POST: Admin/AdminOrders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderId,CustomerId,OrderDate,ShipDate,TransactStatusId,Deleted,Paid,PaymentDate,PaymentId,Note,TotalMoney,Address,LocationId,District,Ward")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustomerId", "CustomerId", order.CustomerId);
            ViewData["TransactStatusId"] = new SelectList(_context.TransactStatuses, "TransactStatusId", "TransactStatusId", order.TransactStatusId);
            return View(order);
        }

        // GET: Admin/AdminOrders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustomerId", "CustomerId", order.CustomerId);
            ViewData["TrangThai"] = new SelectList(_context.TransactStatuses, "TransactStatusId", "Status", order.TransactStatusId);
            return View(order);
        }

        // POST: Admin/AdminOrders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OrderId,CustomerId,OrderDate,ShipDate,TransactStatusId,Deleted,Paid,PaymentDate,PaymentId,Note,TotalMoney,Address,LocationId,District,Ward")] Order order)
        {
            if (id != order.OrderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var donhang = await _context.Orders.AsNoTracking().Include(x => x.Customer).FirstOrDefaultAsync(x => x.OrderId == id);
                    if (donhang != null)
                    {
                        donhang.Paid = order.Paid;
                        donhang.Deleted = order.Deleted;
                        donhang.TransactStatusId = order.TransactStatusId;
                        if (donhang.Paid == true)
                        {
                            donhang.PaymentDate = DateTime.Now;
                        }
                        if (donhang.TransactStatusId == 5) donhang.Deleted = true;
                        if (donhang.TransactStatusId == 3) donhang.ShipDate = DateTime.Now;
                    }
                    _context.Update(donhang);
                    await _context.SaveChangesAsync();
                    _notyfService.Success("Cập nhật trạng thấy thành công thành công");
                }
                catch (DbUpdateConcurrencyException)
                {

VGSShop/Areas/Admin/Views/AdminOrders/ChangeStatus.cshtml
@model VGSShop.Models.Order

<div class="modal-header">
    <h5 class="modal-title">THÔNG TIN ĐƠN HÀNG</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">THÔNG TIN ĐƠN HÀNG #@Model.OrderId</h4>
            <div class="table-responsive">
                <table class="product-info-table m-t-20">
                    <tbody>
                        <tr>
                            <td>ID: </td>
                            <td class="text-dark font-weight-semibold">#@Model.OrderId</td>
                        </tr>
                        <tr>
                            <td>Ngày mua hàng: </td>
                            <td>@Model.OrderDate</td>
                        </tr>
                        <tr>
                            <td>Khách hàng: </td>
                            <td>@Model.Customer.FullName</td>
                        </tr>
                        <tr>
                            <td>Số điện thoại: </td>
                            <td>@Model.Customer.Phone</td>
                        </tr>
                        <tr>
                            <td>Địa chỉ: </td>
                            <td>@Model.Customer.Adress</td>
                        </tr>
                        <tr>
                            <td>Tổng tiền: </td>
                            <td>@Model.TotalMoney.ToString("#.##0")</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <form asp-area="Admin" asp-controller="AdminOrders" asp-action="ChangeStatus" asp-route-id="@Model.OrderId" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="OrderId" />
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Chọn trạng thái đơn hàng</label>
                            <select class="form-control" asp-for="TransactStatusId" asp-items="ViewBag.TrangThai">
                                <option value="0" disabled selected> Lựa chọn trạng thái</option>
                            </select>
                        </div>
                    </div>
                </div>
                @*<div class="form-group">
                    <label>Đã thanh toán</label>
                    <input asp-for="Paid" type="checkbox" />
                    <span asp-validation-for="Paid" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label>Đơn hàng bị hủy</label>
                    <input asp-for="Deleted" type="checkbox" />
                    <span asp-validation-for="Deleted" class="text-danger"></span>
                </div>*@
                <button type="submit" class="btn btn-success">LƯU</button>
            </form>
        </div>
    </div>
</div>

VGSShop/Areas/Admin/Views/AdminOrders/Create.cshtml
@model VGSShop.Models.Order

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                <select asp-for="CustomerId" class ="form-control" asp-items="ViewBag.CustomerId"></select>
            </div>
            <div class="form-group">
                <label asp-for="OrderDate" class="control-label"></label>
                <input asp-for="OrderDate" class="form-control" />
                <span asp-validation-for="OrderDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShipDate" class="control-label"></label>
                <input asp-for="ShipDate" class="form-control" />
                <span asp-validation-for="ShipDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TransactStatusId" class="control-label"></label>
                <select asp-for="TransactStatusId" class ="form-control" asp-items="ViewBag.TransactStatusId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Deleted" class="control-label"></label>
                <input asp-for="Deleted" class="form-control" />
                <span asp-validation-for="Deleted" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Paid" class="control-label"></label>
                <input asp-for="Paid" class="form-control" />
                <span asp-validation-for="Paid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaymentDate" class="control-label"></label>
                <input asp-for="PaymentDate" class="form-control" />
                <span asp-validation-for="PaymentDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaymentId" class="control-label"></label>
                <input asp-for="PaymentId" class="form-control" />
                <span asp-validation-for="PaymentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Note" class="control-label"></label>
                <input asp-for="Note" class="form-control" />
                <span asp-validation-for="Note" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalMoney" class="control-label"></label>
                <input asp-for="TotalMoney" class="form-control" />
                <span asp-validation-for="TotalMoney" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocationId" class="control-label"></label>
                <input asp-for="LocationId" class="form-control" />
                <span asp-validation-for="LocationId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="District" class="control-label"></label>
                <input asp-for="District" class="form-control" />
                <span asp-validation-for="District" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ward" class="control-label"></label>
                <input asp-for="Ward" class="form-control" />
                <span asp-validation-for="Ward" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

VGSShop/Areas/Admin/Views/AdminOrders/Delete.cshtml
@model VGSShop.Models.Order

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
    List<OrderDetail> orderDetails = ViewBag.ChiTiet;
}

<div class="page-container">


    <!-- Content Wrapper START -->
    <div class="main-content">
        <div class="page-header">
            <div class="header-sub-title">
                <nav class="breadcrumb breadcrumb-dash">
                    <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
                    <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminOrders" asp-action="Index">Danh sách sản phẩm</a>
                    <span class="breadcrumb-item active">Thông tin đơn hàng :KH - @Model.Customer.FullName.ToUpper()</span>
                </nav>
            </div>
        </div>
        <div class="container">
            <div class="card">
                <div class="card-body">
                    <div id="invoice" class="p-h-30">
                        <div class="row m-t-20 lh-2">
                            <div class="col-sm-7">
                                <h3 class="p-l-10 m-t-10">ĐƠN HÀNG:</h3>
                                <span class="font-weight-semibold text-dark">@Model.Customer.FullName.ToUpper()</span><br>
                                <abbr class="text-dark" title="Address">Địa chỉ giao hàng</abbr>
                                <span>@Model.Address</span><br>
                                <abbr class="text-dark" title="Phone">Số điện thoại:</abbr>
                                <span>@Model.Customer.Phone</span>
                            </div>
                            <div class="col-sm-5">
                                <div class="m-t-80">
                                    <div class="text-dark text-uppercase d-inline-block">
                                        <span class="font-weight-semibold text-dark">THÔNG TIN MUA HÀNG</span>
                                    </div>
                                    <div class="float-right">MS-@Model.OrderId</div>
                                </div>
                                <div class="text-dark text-uppercase d-inline-block">
                                    <span class="font-weight-semibold text-dark">Ngày mua:</span>
                                </div>
                                <div class="float-right">@Model.OrderDate</div>
                                <div class="text-dark text-uppercase d-inline-block">
                                    <span class="font-weight-semibold text-dark">Ngày ship hàng:</span>
                                </div>
                                <div class="float-right">@Model.ShipDate</div>
                                <div class="text-dark text-uppercase d-inline-block">
                                    <span class="font-weight-semibold text-dark">Trạng thái đơn hàng:</span>
                                </div>
                                <div class="float-right">@Model.TransactStatus.Status</div>
                            </div>
                        </div>
                        <div class="m-t-20">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>STT</th>
                                            <th>SẢN PHẨM
                                            <th>
                                            <th>SỐ LƯỢNG</th>
                                            <th></th>
                                            <th>ĐƠN GIÁ</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (orderDetails != null && orderDetails.Count() > 0)
                                        {
                                            int i = 1;
                                            foreach (var item in orderDetails)
                                            {
                                                string url = $"/{item.Product.Alias}-{item.Product.ProductId}.html";
                                                <tr>
                                                    <td>@i</td>
                                                    <td><a href="@url">@item.Product.ProductName</a></td>
                                                    <td></td>
                                                    <td>@item.Quantity</td>
                                                    <td></td>
                                                    <td>@item.Price.ToString("#,##0") VNĐ</td>
                                                </tr>
                                                i++;
                                            }

                                        }
                                    </tbody>
                                </table>
                            </div>
                            <div class="row m-t-30 lh-1-8">
                                <div class="col-sm-12">
                                    <div class="float-right text-right">
                                        <hr>
                                        <h3><span class="font-weight-semibold text-dark">TỔNG TIỀN :</span> @Model.TotalMoney.ToString("#,##0") VNĐ</h3>
                                    </div>
                                </div>
                            </div>
                            <form asp-action="Delete">
                                <input type="hidden" asp-for="OrderId" />
                                <input type="submit" value="XÓA ĐƠN HÀNG" class="btn btn-danger" /> 
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

VGSShop/Areas/Admin/Views/AdminOrders/Details.cshtml
@model VGSShop.Models.Order

@{
    ViewData["Title"] = "Thông tin đơn hàng #" + Model.OrderId;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
    List<OrderDetail> orderDetails = ViewBag.ChiTiet;
}



<!-- Content Wrapper START -->
<div class="main-content">
    <div class="page-header">
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
                <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminOrders" asp-action="Index">Danh sách sản phẩm</a>
                <span class="breadcrumb-item active">Thông tin đơn hàng :KH - @Model.Customer.FullName.ToUpper()</span>
            </nav>
        </div>
    </div>
    <div class="container">
        <div class="card">
            <div class="card-body">
                <div id="invoice" class="p-h-30">
                    <div class="row m-t-20 lh-2">
                        <div class="col-sm-7">
                            <h3 class="p-l-10 m-t-10">ĐƠN HÀNG:</h3>
                            <span class="font-weight-semibold text-dark">@Model.Customer.FullName.ToUpper()</span><br>
                            <abbr class="text-dark" title="Address">Địa chỉ giao hàng</abbr>
                            <span>@Model.Address</span><br>
                            <abbr class="text-dark" title="Phone">Số điện thoại:</abbr>
                            <span>@Model.Customer.Phone</span>
                        </div>
                        <div class="col-sm-5">
                            <div class="m-t-80">
                                <div class="text-dark text-uppercase d-inline-block">
                                    <span class="font-weight-semibold text-dark">THÔNG TIN MUA HÀNG</span>
                                </div>
                                <div class="float-right">MS-@Model.OrderId</div>
                            </div>
                            <div class="text-dark text-uppercase d-inline-block">
                                <span class="font-weight-semibold text-dark">Ngày mua:</span>
                            </div>
                            <div class="float-right">@Model.OrderDate</div>
                            <div class="text-dark text-uppercase d-inline-block">
                                <span class="font-weight-semibold text-dark">Ngày ship hàng:</span>
                            </div>
                            <div class="float-right">@Model.ShipDate</div>
                            <div class="text-dark text-uppercase d-inline-block">
                                <span class="font-weight-semibold text-dark">Trạng thái đơn hàng:</span>
                            </div>
                            <div class="float-right">@Model.TransactStatus.Status</div>
                        </div>
                    </div>
                    <div class="m-t-20">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>STT</th>
                                        <th>SẢN PHẨM
                                        <th>
                                        <th>SỐ LƯỢNG</th>
                                        <th></th>
                                        <th>ĐƠN GIÁ</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (orderDetails != null && orderDetails.Count() > 0)
                                    {
                                        int i = 1;
                                        foreach (var item in orderDetails)
                                        {
                                            string url = $"/{item.Product.Alias}-{item.Product.ProductId}.html";
                                            <tr>
                                                <td>@i</td>
                                                <td><a href="@url">@item.Product.ProductName</a></td>
                                                <td></td>
                                                <td>@item.Quantity</td>
                                                <td></td>
                                                <td>@item.Price.ToString("#,##0") VNĐ</td>
                                            </tr>
                                            i++;
                                        }

                                    }
                                </tbody>
                            </table>
                        </div>
                        <div class="row m-t-30 lh-1-8">
                            <div class="col-sm-12">
                                <div class="float-right text-right">
                                    <hr>
                                    <h3><span class="font-weight-semibold text-dark">TỔNG TIỀN :</span> @Model.TotalMoney.ToString("#,##0") VNĐ</h3>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Content Wrapper END -->

VGSShop/Areas/Admin/Views/AdminOrders/Edit.cshtml
@model VGSShop.Models.Order

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="modal-header">
    <h5 class="modal-title">THÔNG TIN ĐƠN HÀNG</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <div class="card">
        <div class="card-body">
            <form asp-area="Admin" asp-controller="AdminOrders" asp-action="Edit" asp-route-id="@Model.OrderId" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="OrderId" />
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Chọn trạng thái đơn hàng</label>
                            <select class="form-control" asp-for="TransactStatusId" asp-items="ViewBag.TrangThai">
                                <option value="0" disabled selected> Lựa chọn trạng thái</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label>Đã thanh toán</label>
                    <input asp-for="Paid" type="checkbox" />
                    <span asp-validation-for="Paid" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label>Đơn hàng bị hủy</label>
                    <input asp-for="Deleted" type="checkbox" />
                    <span asp-validation-for="Deleted" class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-success">LƯU</button>
            </form>
        </div>
    </div>
</div>