VGSShop/Areas/Admin/Controllers/AdminRolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VGSShop.Models;

namespace VGSShop.Areas.Admin.Controllers
{
    [Area("Admin")]

    public class AdminRolesController : Controller
    {
        private readonly VGSShopContext _context;
        public INotyfService _notyfService { get; }

        public AdminRolesController(VGSShopContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        // GET: Admin/AdminRoles
        public async Task<IActionResult> Index()
        {
            if (!User.Identity.IsAuthenticated) Response.Redirect("/dang-nhap-admin.html");
            var taiKhoanID = HttpContext.Session.GetString("AccountId");
            if (taiKhoanID == null) return RedirectToAction("Login", "Account", new { Area = "Admin" });
            var admin = _context.Accounts.AsNoTracking()
                    .SingleOrDefault(x => x.AccountId == Convert.ToInt32(taiKhoanID));
            if (admin.RoleId != 4)
            {
                _notyfService.Warning("Chỉ quản trị viên mới được phép sửa dụng chức năng này");
                return RedirectToAction("Index", "AdminHome", new { Area = "Admin" });
            }
            else
            {
                return View(await _context.Roles.ToListAsync());
            }
           
        }

        // GET: Admin/AdminRoles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles
                .FirstOrDefaultAsync(m => m.RoleId == id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // GET: Admin/AdminRoles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminRoles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RoleId,RoleName,Description")] Role role)
        {
            if (ModelState.IsValid)
            {
                _context.Add(role);
                await _context.SaveChangesAsync();
                _notyfService.Success("Thêm mới thành công");
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: Admin/AdminRoles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles.FindAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        // POST: Admin/AdminRoles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RoleId,RoleName,Description")] Role role)
        {
            if (id != role.RoleId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(role);
                    await _context.SaveChangesAsync();
                    _notyfService.Success("Cập nhật thành công");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoleExists(role.RoleId))
                    {
                        _notyfService.Success("Có lỗi xảy ra");
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: Admin/AdminRoles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles
                .FirstOrDefaultAsync(m => m.RoleId == id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // POST: Admin/AdminRoles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var role = await _context.Roles.FindAsync(id);
            _context.Roles.Remove(role);
            await _context.SaveChangesAsync();
            _notyfService.Success("Xóa quyền truy cập thành công");
            return RedirectToAction(nameof(Index));
        }

        private bool RoleExists(int id)
        {
            return _context.Roles.Any(e => e.RoleId == id);
        }
    }
}

VGSShop/Areas/Admin/Views/AdminRoles/Create.cshtml
@model VGSShop.Models.Role

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminRoles" asp-action="Index">Danh sách quyền truy cập</a>
            <span class="breadcrumb-item active">Tạo mới quyền truy cập</span>
        </nav>
    </div>
</div>
@*<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="RoleId" />
    <div class="form-group">
        <div class="form-group col-md-6">
            <label class="col-sm-2 col-form-label">Tên</label>
            <div class="col-sm-6">
                <input type="text" class="form-control" asp-for="RoleName" placeholder="Tên quyền truy cập">
            </div>
        </div>
        <div class="form-group col-md-6">
            <label class="col-sm-3 col-form-label">Mô tả quyền</label>
            <div class="col-sm-6">
                <input type="text" class="form-control" asp-for="Description" placeholder="Mô tả">
            </div>
        </div>
        <div class="form-group col-md-6">
            <div class="col-sm-6">
                <button type="submit" class="btn btn-primary">Tạo mới</button>
            </div>
        </div>
    </div>
</form>*@

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RoleName" class="control-label">Tên quyền: </label>
                <input asp-for="RoleName" class="form-control" />
                <span asp-validation-for="RoleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Mô tả: </label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

VGSShop/Areas/Admin/Views/AdminRoles/Delete.cshtml
@model VGSShop.Models.Role

@{
    ViewData["Title"] = "Xác nhận xóa quyền truy cập";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminRoles" asp-action="Index">Danh sách quyền truy cập</a>
            <span class="breadcrumb-item active">Xóa quyền truy cập</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Bạn muốn xóa quyền truy cập này ?</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20"> 
                <tbody>
                    <tr>
                        <td class="text-dark font-weight-bold">ID:</td>
                        <td class="text-dark font-weight-semibold">@Model.RoleId</td>
                    </tr>
                    <tr>
                        <td class="text-dark font-weight-bold">Tên quyền truy cập:</td>
                        <td class="text-dark font-weight-semibold">@Model.RoleName</td>
                    </tr>
                    <tr>
                        <td class="text-dark font-weight-bold">Mô tả:</td>
                        <td class="text-dark font-weight-semibold">@Model.Description</td>
                    </tr>
                    <tr>
                        <td class="text-dark font-weight-bold">Xác nhận XÓA: </td>
                        <td>
                            <form asp-action="Delete" asp-route-id="@Model.RoleId">
                                <input type="hidden" asp-for="RoleId"/>
                                <input type="submit" value="Delete" class="btn btn-danger m-r-5" />
                            </form>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

VGSShop/Areas/Admin/Views/AdminRoles/Details.cshtml
@model VGSShop.Models.Role

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Role</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoleName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoleName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.RoleId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

VGSShop/Areas/Admin/Views/AdminRoles/Edit.cshtml
@model VGSShop.Models.Role

@{
    ViewData["Title"] = "Chỉnh sửa quyền truy cập";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminRoles" asp-action="Index">Danh sách quyền truy cập</a>
            <span class="breadcrumb-item active">Chỉnh sửa quyền truy cập</span>
        </nav>
    </div>
</div>
<form asp-action="Edit" asp-route-id="@Model.RoleId" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="RoleId" />
    <div class="form-group">
        <div class="form-group col-md-6">
            <label class="col-sm-2 col-form-label">Tên</label>
            <div class="col-sm-6">
                <input type="text" class="form-control" asp-for="RoleName" placeholder="Tên quyền truy cập">
            </div>
        </div>
        <div class="form-group col-md-6">
            <label class="col-sm-3 col-form-label">Mô tả quyền</label>
            <div class="col-sm-6">
                <input type="text" class="form-control" asp-for="Description" placeholder="Mô tả">
            </div>
        </div>
        <div class="form-group col-md-6">
            <div class="col-sm-6">
                <button type="submit" class="btn btn-primary">Lưu lại</button>
            </div>
        </div>
    </div>
</form>

VGSShop/Areas/Admin/Views/AdminRoles/Index.cshtml
@model IEnumerable<VGSShop.Models.Role>

@{
    ViewData["Title"] = "Danh sách quyền truy cập";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Danh sách quyền truy cập</h1>

<p>
    <a class="btn btn-primary m-r-5" asp-action="Create">Thêm mới</a>
</p>
<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Tên quyền</th>
                <th scope="col">Mô tả</th>
                <th scope="col">Thao tác</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null)
            {
                foreach (var item in Model)
                {
                    <tr>
                        <th scope="row">@item.RoleId</th>
                        <td>@item.RoleName</td>
                        <td>@item.Description</td>
                        <td>
                            <a class="btn btn-warning btn-tone m-r-5" asp-action="Edit" asp-route-id="@item.RoleId">Chỉnh sửa</a>                          
                            @*<a class="btn btn-danger btn-tone m-r-5" asp-action="Delete" asp-route-id="@item.RoleId">Delete</a>*@
                        </td>
                    </tr>

                }
            }
        </tbody>
    </table>
</div>