VGSShop/Areas/Admin/Controllers/AdminNewsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;
using VGSShop.Helpers;
using VGSShop.Models;

namespace VGSShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize()]
    public class AdminNewsController : Controller
    {
        private readonly VGSShopContext _context;
        public INotyfService _notyfService { get; }
        public AdminNewsController(VGSShopContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        // GET: Admin/AdminNews
        public async Task<IActionResult> Index(int? page)
        {
            if (!User.Identity.IsAuthenticated) Response.Redirect("/dang-nhap-admin.html");
            var taiKhoanID = HttpContext.Session.GetString("AccountId");
            if (taiKhoanID == null) return RedirectToAction("Login", "Account", new { Area = "Admin" });
            var admin = _context.Accounts.AsNoTracking()
                    .SingleOrDefault(x => x.AccountId == Convert.ToInt32(taiKhoanID));

            List<News> lsNews = new List<News>();

            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = Utilities.PAGE_SIZE; //20

            if (admin.RoleId == 4)
            {
                lsNews = _context.News
                .AsNoTracking()
                .OrderByDescending(x => x.PostId).ToList();
            }
            else
            {
                lsNews = _context.News
                .AsNoTracking()
                .Where(x =>x.AccountId == admin.AccountId )
                .OrderByDescending(x => x.PostId).ToList();
            }
            PagedList<News> models = new PagedList<News>(lsNews.AsQueryable(), pageNumber, pageSize);
            ViewBag.CurrentPage = pageNumber;
            return View(models);
        }

        // GET: Admin/AdminNews/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var news = await _context.News
                .FirstOrDefaultAsync(m => m.PostId == id);
            if (news == null)
            {
                return NotFound();
            }

            return View(news);
        }

        // GET: Admin/AdminNews/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminNews/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PostId,Title,Scontents,Contents,Thumb,Published,Alias,CreatedDate,Author,AccountId,Tags,CatId,IsHot,IsNewfeed,MetaKey,MetaDesc,Views")] News news, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (!User.Identity.IsAuthenticated) Response.Redirect("/dang-nhap-admin.html");
            var taiKhoanID = HttpContext.Session.GetString("AccountId");
            if (taiKhoanID == null) return RedirectToAction("Login", "Account", new { Area = "Admin" });
            var admin = _context.Accounts.AsNoTracking()
                    .SingleOrDefault(x => x.AccountId == Convert.ToInt32(taiKhoanID));

            if (ModelState.IsValid)
            {
                //Xử lý hình ảnh thumb
                if (fThumb != null)
                {
                    string extension = Path.GetExtension(fThumb.FileName);
                    string image = Utilities.ToUnsignString(news.Title) + extension;
                    news.Thumb = await Utilities.UploadFile(fThumb, @"news", image.ToLower());
                }
                if (string.IsNullOrEmpty(news.Thumb)) news.Thumb = "default.jpg";
                news.Alias = Utilities.ToUnsignString(news.Title);
                news.CreatedDate = DateTime.Now;
                news.Author = admin.FullName;
                news.AccountId = admin.AccountId;
                _context.Add(news);
                await _context.SaveChangesAsync();
                _notyfService.Success("Thêm mới thành công");
                return RedirectToAction(nameof(Index));
            }
            return View(news);
        }

        // GET: Admin/AdminNews/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var news = await _context.News.FindAsync(id);
            if (news == null)
            {
                return NotFound();
            }
            return View(news);
        }

        // POST: Admin/AdminNews/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PostId,Title,Scontents,Contents,Thumb,Published,Alias,CreatedDate,Author,AccountId,Tags,CatId,IsHot,IsNewfeed,MetaKey,MetaDesc,Views")] News news, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (!User.Identity.IsAuthenticated) Response.Redirect("/dang-nhap-admin.html");
            var taiKhoanID = HttpContext.Session.GetString("AccountId");
            if (taiKhoanID == null) return RedirectToAction("Login", "Account", new { Area = "Admin" });
            var admin = _context.Accounts.AsNoTracking()
                    .SingleOrDefault(x => x.AccountId == Convert.ToInt32(taiKhoanID));
            if (id != news.PostId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                { //Xử lý hình ảnh thumb
                    if (fThumb != null)
                    {
                        string extension = Path.GetExtension(fThumb.FileName);
                        string image = Utilities.ToUnsignString(news.Title) + extension;
                        news.Thumb = await Utilities.UploadFile(fThumb, @"news", image.ToLower());
                    }
                    if (string.IsNullOrEmpty(news.Thumb)) news.Thumb = "default.jpg";
                    news.Alias = Utilities.ToUnsignString(news.Title);
                    _context.Update(news);
                    await _context.SaveChangesAsync();
                    _notyfService.Success("Chỉnh sửa thành công");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NewsExists(news.PostId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(news);
        }

        // GET: Admin/AdminNews/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var news = await _context.News
                .FirstOrDefaultAsync(m => m.PostId == id);
            if (news == null)
            {
                return NotFound();
            }

            return View(news);
        }

        // POST: Admin/AdminNews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var news = await _context.News.FindAsync(id);
            _context.News.Remove(news);
            await _context.SaveChangesAsync();
            _notyfService.Success("Xóa thành công");
            return RedirectToAction(nameof(Index));
        }

        private bool NewsExists(int id)
        {
            return _context.News.Any(e => e.PostId == id);
        }
    }
}

VGSShop/Areas/Admin/Views/AdminNews/Create.cshtml
@model VGSShop.Models.News

@{
    ViewData["Title"] = "Thêm mới bài viết tin tức";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
@section Styles{
    <link href="~/summernote/summernote.css" rel="stylesheet" />
    <link href="~/summernote/summernote-bs4.css" rel="stylesheet" />
}
<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminNews" asp-action="Index">Danh sách tin tức</a>
            <span class="breadcrumb-item active">Tạo mới tin</span>
        </nav>
    </div>
</div>
<form asp-controller="AdminNews" asp-action="Create" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="media align-items-center m-b-15">

            </div>
            <div class="m-b-15">
                <button class="btn btn-primary">
                    <i class="anticon anticon-save"></i>
                    <span>LƯU</span>
                </button>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">THÔNG TIN TIN TỨC</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-option">THÔNG TIN SEO</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-description">MÔ TẢ</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Tiêu đề</label>
                        <input type="text" class="form-control" asp-for="Title">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productBrand">Hình ảnh đại diện</label>
                        <input name="fThumb" type="file" class="form-control-file" asp-for="Thumb">
                        <span asp-validation-for="Thumb" class="text-danger"></span>
                    </div>
                    <div class="row">
                        <div class="m-t-25">
                            <div class="form-group d-flex align-items-center">
                                <div class="switch m-r-10">
                                    <input type="checkbox" asp-for="Published" checked="">
                                    <label for="Published"></label>
                                </div>
                                <label>Kích hoạt</label>
                            </div>
                            <div class="form-group d-flex align-items-center">
                                <div class="switch m-r-10">
                                    <input type="checkbox" asp-for="IsHot" checked="">
                                    <label for="IsHot"></label>
                                </div>
                                <label>Tin HOT</label>
                            </div>
                            <div class="form-group d-flex align-items-center">
                                <div class="switch m-r-10">
                                    <input type="checkbox" asp-for="IsNewfeed" checked="">
                                    <label for="IsNewfeed"></label>
                                </div>
                                <label>Hiện thị</label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-option">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productColors">MetaDesc</label>
                        <input type="text" class="form-control" asp-for="MetaDesc">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">MetaKey</label>
                        <input type="text" class="form-control" asp-for="MetaKey">
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-description">
            <div class="card">
                <div class="card-body">
                    <textarea class="summernote" asp-for="Contents"></textarea>
                </div>
            </div>
        </div>
    </div>
</form>
@section Script {
    <script src="~/AdminAssets/vendors/select2/select2.min.js"></script>
    <script src="~/AdminAssets/js/pages/e-commerce-product-edit.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/jquery.validate.min.js"></script>
    <script src="~/summernote/summernote-bs4.js"></script>
    <script>
        jQuery(document).ready(function () {
            $('.summernote').summernote({
                fontNames: ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New'],
                styleTags: ['p', 'h1', 'h2', 'h3', 'h4', 'h5'],
                height: 200,                 // set editor height
                minHeight: null,             // set minimum height of editor
                maxHeight: null,             // set maximum height of editor
                focus: true
            });
        })
    </script>
}

VGSShop/Areas/Admin/Views/AdminNews/Delete.cshtml
@model VGSShop.Models.News

@{
    ViewData["Title"] = "Xóa bài viết : " + Model.Title;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminNews" asp-action="Index">Danh sách bài viết</a>
            <span class="breadcrumb-item active">Xóa bài viết : @Model.Title</span>
        </nav>
    </div>
</div>
<div class="page-header no-gutters has-tab">
    <div class="d-md-flex m-b-15 align-items-center justify-content-between">
        <div class="media align-items-center m-b-15">
            <div class="avatar avatar-image rounded" style="height: 70px; width: 100px">
                <img src="~/images/news/@Model.Thumb" alt="@Model.Title">
            </div>
            <div class="m-l-15">
                <h4 class="m-b-0">@Model.Title</h4>
                <p class="text-muted m-b-0">ID: #@Model.PostId</p>
            </div>
        </div>

    </div>
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">THÔNG TIN BÀI VIẾT</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#product-images">HÌNH ẢNH</a>
        </li>
    </ul>
</div>
<div class="container-fluid">
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <h1 class="card-title">XÁC NHẬN XÓA BÀI: @Model.Title.ToUpper()</h1>
                    <div class="table-responsive">
                        <form asp-action="Delete" asp-route-id="@Model.PostId">
                            <input type="hidden" asp-for="PostId" />
                            <table class="product-info-table m-t-20">

                                <tbody>
                                    <tr>
                                        <td class="text-dark font-weight-semibold">Tên bài viết:</td>
                                        <td>@Model.Title</td>
                                    </tr>
                                    <tr>
                                        <td class="text-dark font-weight-semibold">Alias:</td>
                                        <td>@Model.Alias</td>
                                    </tr>
                                    <tr>
                                        <td class="text-dark font-weight-semibold">Trạng thái:</td>
                                        <td>
                                            <div class="checkbox">
                                                <input asp-for="Published" type="checkbox" />
                                                <label for="Published">Công khai</label>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="text-dark font-weight-semibold">Xác nhận XÓA</td>
                                        <td>
                                            <input type="submit" value="XÓA" class="btn btn-danger" />
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </form>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Thôn tin mô tả</h4>
                </div>
                <div class="card-body">
                    @Html.Raw(Model.Contents)
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-images">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <img class="img-fluid" src="~/images/news/@Model.Thumb" alt="@Model.Title">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

VGSShop/Areas/Admin/Views/AdminNews/Details.cshtml
@model VGSShop.Models.News

@{
    ViewData["Title"] = Model.Title;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminNews" asp-action="Index">Danh sách tin tức</a>
            <span class="breadcrumb-item active">@Model.Title</span>
        </nav>
    </div>
</div>
<div class="page-header no-gutters has-tab">
    <div class="d-md-flex m-b-15 align-items-center justify-content-between">
        <div class="media align-items-center m-b-15">
            <div class="avatar avatar-image rounded" style="height: 70px; width: 100px">
                <img src="~/images/news/@Model.Thumb" alt="@Model.Title">
            </div>
            <div class="m-l-15">
                <h4 class="m-b-0">@Model.Title</h4>
                <p class="text-muted m-b-0">ID: #@Model.PostId</p>
            </div>
        </div>
        <div class="m-b-15">
            <a class="btn btn-primary" asp-area="Admin" asp-controller="AdminNews" asp-action="Edit" asp-route-id="@Model.PostId"> SỬA</a>
        </div>
    </div>
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">THÔNG TIN BÀI VIẾT</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#product-images">HÌNH ẢNH</a>
        </li>
    </ul>
</div>
<div class="container-fluid">
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="product-info-table m-t-20">
                            <tbody>
                                <tr>
                                    <td class="text-dark font-weight-semibold">Tiêu đề:</td>
                                    <td>@Model.Title</td>
                                </tr>
                                <tr>
                                    <td class="text-dark font-weight-semibold">Alias:</td>
                                    <td>@Model.Alias</td>
                                </tr>
                                <tr>
                                    <td class="text-dark font-weight-semibold">Trạng thái:</td>
                                    <td>
                                        <div class="checkbox">
                                            <input asp-for="Published" type="checkbox" />
                                            <label for="Published">Công khai</label>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="text-dark font-weight-semibold">Tin HOT:</td>
                                    <td>
                                        <div class="checkbox">
                                            <input asp-for="IsHot" type="checkbox" />
                                            <label for="IsHot">HOT</label>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="text-dark font-weight-semibold">Đăng bài:</td>
                                    <td>
                                        <div class="checkbox">
                                            <input asp-for="IsNewfeed" type="checkbox" />
                                            <label for="IsNewfeed">ĐĂNG</label>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Thôn tin mô tả</h4>
                </div>
                <div class="card-body">
                    @Html.Raw(Model.Contents)
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-images">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <img class="img-fluid" src="~/images/news/@Model.Thumb" alt="@Model.Title">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

VGSShop/Areas/Admin/Views/AdminNews/Edit.cshtml
@model VGSShop.Models.News

@{
    ViewData["Title"] = "Chỉnh sửa bài viết tin tức";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
@section Styles{
    <link href="~/summernote/summernote.css" rel="stylesheet" />
    <link href="~/summernote/summernote-bs4.css" rel="stylesheet" />
}
<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" asp-route-id="@Model.PostId" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminNews" asp-action="Index">Danh sách tin tức</a>
            <span class="breadcrumb-item active">CHỈNH SỬA : @Model.Title</span>
        </nav>
    </div>
</div>
<form asp-controller="AdminNews" asp-action="Edit" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="PostId" />
    <input type="hidden" asp-for="Thumb" />
    <input type="hidden" asp-for="CreatedDate" />
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="media align-items-center m-b-15">

            </div>
            <div class="m-b-15">
                <button class="btn btn-primary">
                    <i class="anticon anticon-save"></i>
                    <span>LƯU</span>
                </button>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">THÔNG TIN TIN TỨC</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-description">MÔ TẢ</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Tiêu đề</label>
                        <input type="text" class="form-control" asp-for="Title">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productBrand">Hình ảnh đại diện</label>
                        <input name="fThumb" type="file" class="form-control-file" asp-for="Thumb">
                        <span asp-validation-for="Thumb" class="text-danger"></span>
                    </div>
                    <div class="row">
                        <div class="m-t-25">
                            <div class="form-group d-flex align-items-center">
                                <div class="switch m-r-10">
                                    <input type="checkbox" asp-for="Published" checked="">
                                    <label for="Published"></label>
                                </div>
                                <label>Kích hoạt</label>
                            </div>
                            <div class="form-group d-flex align-items-center">
                                <div class="switch m-r-10">
                                    <input type="checkbox" asp-for="IsHot" checked="">
                                    <label for="IsHot"></label>
                                </div>
                                <label>Tin HOT</label>
                            </div>
                            <div class="form-group d-flex align-items-center">
                                <div class="switch m-r-10">
                                    <input type="checkbox" asp-for="IsNewfeed" checked="">
                                    <label for="IsNewfeed"></label>
                                </div>
                                <label>Hiện thị</label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-option">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productColors">MetaDesc</label>
                        <input type="text" class="form-control" asp-for="MetaDesc">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productFit">MetaKey</label>
                        <input type="text" class="form-control" asp-for="MetaKey">
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-description">
            <div class="card">
                <div class="card-body">
                    <textarea class="summernote" asp-for="Contents"></textarea>
                </div>
            </div>
        </div>
    </div>
</form>
@section Script {
    <script src="~/AdminAssets/vendors/select2/select2.min.js"></script>
    <script src="~/AdminAssets/js/pages/e-commerce-product-edit.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/jquery.validate.min.js"></script>
    <script src="~/summernote/summernote-bs4.js"></script>
    <script>
        jQuery(document).ready(function () {
            $('.summernote').summernote({
                fontNames: ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New'],
                styleTags: ['p', 'h1', 'h2', 'h3', 'h4', 'h5'],
                height: 200,                 // set editor height
                minHeight: null,             // set minimum height of editor
                maxHeight: null,             // set maximum height of editor
                focus: true
            });
        })
    </script>
}